### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by zclancy** [originalmachine/fleek#1]
I don't think you should have bumped the version number for fixing code that was originally broken.

**Comment by nicholaswyoung** [comment]
1.0.0 was on npm and required a patch level bump to republish.

**Comment by rgarrison3** [comment]
@zclancy seems like @nicholaswyoung is making this all up.

**Comment by nicholaswyoung** [comment]
@rgarrison3 Hey, if you don't like the module or how I maintain it, nobody says you have to use it. Either find another module or fork and move on.
